SELECT * FROM (
    SELECT 'YOUNGEST' AS type, NAME, BIRTHDAY FROM worker ORDER BY BIRTHDAY ASC LIMIT 1
) AS YoungestWorker
UNION ALL
SELECT * FROM (
    SELECT 'OLDEST' AS type, NAME, BIRTHDAY FROM worker ORDER BY BIRTHDAY DESC LIMIT 1
) AS OldestWorker;
